<?php
    include "setup_session.php";
    if(isset($_GET['pizza_homepage'])){
        $_SESSION['cart'][0]++;
        header("location:../index.php");
    }elseif(isset($_GET['drink_homepage'])){
        $_SESSION['cart'][6]++;
        header("location:../index.php#drink_homepage");
    }elseif(isset($_GET['dessert_homepage'])){
        $_SESSION['cart'][11]++;
        header("location:../index.php#dessert_homepage");
    }elseif(isset($_GET['pizza_dotd'])){
        $_SESSION['cart'][2]++;
        header("location:../deals.php");
    }elseif(isset($_GET['drink_dotd'])){
        $_SESSION['cart'][8]++;
        header("location:../deals.php");
    }elseif(isset($_GET['dessert_dotd'])){
        $_SESSION['cart'][10]++;
        header("location:../deals.php");
    }
?>